// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcDS2X587HIoJ6kU0uxEE7npfd_GFy7xo',
    appId: '1:386654579448:web:3295fc366494504855290d',
    messagingSenderId: '386654579448',
    projectId: 'elibrary-6a547',
    authDomain: 'elibrary-6a547.firebaseapp.com',
    storageBucket: 'elibrary-6a547.firebasestorage.app',
    measurementId: 'G-3BXJRM6N7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEXOuyh5_VNr4_7PXwxAwt_ay1z7pH0EQ',
    appId: '1:386654579448:android:1639156a0305d33a55290d',
    messagingSenderId: '386654579448',
    projectId: 'elibrary-6a547',
    storageBucket: 'elibrary-6a547.firebasestorage.app',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHuBmlN4BTxyU4wBlP_4Uu0qGZy9JlH88',
    appId: '1:386654579448:ios:ee3d1733805c33f255290d',
    messagingSenderId: '386654579448',
    projectId: 'elibrary-6a547',
    storageBucket: 'elibrary-6a547.firebasestorage.app',
    iosBundleId: 'com.elibrary.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHuBmlN4BTxyU4wBlP_4Uu0qGZy9JlH88',
    appId: '1:386654579448:ios:253f4342272ec45e55290d',
    messagingSenderId: '386654579448',
    projectId: 'elibrary-6a547',
    storageBucket: 'elibrary-6a547.firebasestorage.app',
    iosBundleId: 'com.example.templete',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcDS2X587HIoJ6kU0uxEE7npfd_GFy7xo',
    appId: '1:386654579448:web:d96c6cf065a617d155290d',
    messagingSenderId: '386654579448',
    projectId: 'elibrary-6a547',
    authDomain: 'elibrary-6a547.firebaseapp.com',
    storageBucket: 'elibrary-6a547.firebasestorage.app',
    measurementId: 'G-1VQTBCQFJ8',
  );
}
